import { PrismaClient } from '@prisma/client';
import { logger } from '../../shared/utils/logger.util';

/**
 * Popular MCC codes with merchant patterns for intelligent categorization
 * Based on official Visa/Mastercard MCC codes
 */
const MCC_CODES = [
    // Dining & Restaurants
    {
        id: 'mcc_5812',
        code: '5812',
        categoryId: 'cat_dining',
        subCategoryId: 'subcat_restaurants',
        description: 'Eating Places, Restaurants',
        merchantPatterns: [
            'restaurant',
            'eatery',
            'bistro',
            'grill',
            'tavern',
            'diner',
            'steakhouse',
            'pizzeria',
            'sushi',
            'thai',
            'chinese',
            'mexican',
            'italian',
            'indian',
        ],
        tags: ['dining', 'food', 'restaurant'],
        discoveryMethod: 'manual',
        confidence: 1.0,
        verifiedCount: 0,
    },
    {
        id: 'mcc_5814',
        code: '5814',
        categoryId: 'cat_dining',
        subCategoryId: 'subcat_fast_food',
        description: 'Fast Food Restaurants',
        merchantPatterns: [
            'mcdonald',
            'burger',
            'kfc',
            'subway',
            'taco bell',
            'wendys',
            'pizza hut',
            'dominos',
            'chipotle',
            'five guys',
            'in-n-out',
            'chick-fil-a',
            'sonic',
            'arbys',
            'jack in the box',
            'carl jr',
            'white castle',
            'popeyes',
        ],
        tags: ['fast-food', 'quick-service', 'chain'],
        discoveryMethod: 'manual',
        confidence: 1.0,
        verifiedCount: 0,
    },
    {
        id: 'mcc_5813',
        code: '5813',
        categoryId: 'cat_dining',
        subCategoryId: 'subcat_bars',
        description:
            'Drinking Places (Alcoholic Beverages) - Bars, Taverns, Nightclubs',
        merchantPatterns: [
            'bar',
            'pub',
            'tavern',
            'nightclub',
            'lounge',
            'brewery',
            'winery',
            'sports bar',
            'cocktail',
            'saloon',
            'cantina',
            'draft house',
        ],
        tags: ['bar', 'alcohol', 'nightlife'],
        discoveryMethod: 'manual',
        confidence: 1.0,
        verifiedCount: 0,
    },
    {
        id: 'mcc_5499',
        code: '5499',
        categoryId: 'cat_dining',
        subCategoryId: 'subcat_coffee',
        description: 'Miscellaneous Food Stores - Coffee Shops',
        merchantPatterns: [
            'starbucks',
            'coffee',
            'cafe',
            'espresso',
            'dunkin',
            'peets',
            'caribou',
            'tim hortons',
            'costa',
            'java',
            'brew',
            'roasters',
            'bean',
        ],
        tags: ['coffee', 'beverage', 'cafe'],
        discoveryMethod: 'manual',
        confidence: 1.0,
        verifiedCount: 0,
    },

    // Grocery
    {
        id: 'mcc_5411',
        code: '5411',
        categoryId: 'cat_grocery',
        subCategoryId: 'subcat_supermarkets',
        description: 'Grocery Stores, Supermarkets',
        merchantPatterns: [
            'walmart',
            'target',
            'kroger',
            'safeway',
            'publix',
            'wegmans',
            'giant',
            'albertsons',
            'harris teeter',
            'fred meyer',
            'food lion',
            'bi-lo',
            'whole foods',
            'trader joes',
            'aldi',
            'costco',
            'sams club',
            'bjs',
        ],
        tags: ['grocery', 'supermarket', 'food'],
        discoveryMethod: 'manual',
        confidence: 1.0,
        verifiedCount: 0,
    },
    {
        id: 'mcc_5499_convenience',
        code: '5499',
        categoryId: 'cat_grocery',
        subCategoryId: 'subcat_convenience',
        description: 'Miscellaneous Food Stores - Convenience Stores',
        merchantPatterns: [
            '7-eleven',
            'circle k',
            'wawa',
            'sheetz',
            'quick trip',
            'speedway',
            'casey',
            'am pm',
            'racetrac',
            'pilot',
            'loves',
            'flying j',
        ],
        tags: ['convenience', 'quick-mart', 'gas-station-store'],
        discoveryMethod: 'manual',
        confidence: 1.0,
        verifiedCount: 0,
    },
    {
        id: 'mcc_5300',
        code: '5300',
        categoryId: 'cat_grocery',
        subCategoryId: 'subcat_wholesale',
        description: 'Wholesale Clubs',
        merchantPatterns: ['costco', 'sams club', 'bjs', 'warehouse', 'wholesale'],
        tags: ['wholesale', 'bulk', 'membership'],
        discoveryMethod: 'manual',
        confidence: 1.0,
        verifiedCount: 0,
    },

    // Gas & Fuel
    {
        id: 'mcc_5542',
        code: '5542',
        categoryId: 'cat_gas',
        subCategoryId: 'subcat_gas_stations',
        description: 'Automated Fuel Dispensers',
        merchantPatterns: [
            'shell',
            'exxon',
            'chevron',
            'bp',
            'mobil',
            'citgo',
            'marathon',
            'sunoco',
            'phillips 66',
            'conoco',
            'valero',
            'gulf',
            'texaco',
            'arco',
            'circle k',
            'speedway',
            'wawa fuel',
        ],
        tags: ['gas', 'fuel', 'gasoline', 'petrol'],
        discoveryMethod: 'manual',
        confidence: 1.0,
        verifiedCount: 0,
    },
    {
        id: 'mcc_7538',
        code: '7538',
        categoryId: 'cat_gas',
        subCategoryId: 'subcat_auto_services',
        description: 'Automotive Service Shops (Non-Dealer)',
        merchantPatterns: [
            'jiffy lube',
            'valvoline',
            'midas',
            'firestone',
            'goodyear',
            'auto zone',
            'advance auto',
            'pep boys',
            'car wash',
            'oil change',
        ],
        tags: ['automotive', 'maintenance', 'repair'],
        discoveryMethod: 'manual',
        confidence: 1.0,
        verifiedCount: 0,
    },

    // Travel
    {
        id: 'mcc_3000',
        code: '3000',
        categoryId: 'cat_travel',
        subCategoryId: 'subcat_airlines',
        description: 'Airlines',
        merchantPatterns: [
            'american airlines',
            'delta',
            'united',
            'southwest',
            'jetblue',
            'alaska air',
            'spirit',
            'frontier',
            'allegiant',
            'hawaiian',
        ],
        tags: ['airline', 'flight', 'travel'],
        discoveryMethod: 'manual',
        confidence: 1.0,
        verifiedCount: 0,
    },
    {
        id: 'mcc_3504',
        code: '3504',
        categoryId: 'cat_travel',
        subCategoryId: 'subcat_hotels',
        description: 'Hotels, Motels, Resorts',
        merchantPatterns: [
            'marriott',
            'hilton',
            'hyatt',
            'intercontinental',
            'sheraton',
            'westin',
            'doubletree',
            'courtyard',
            'residence inn',
            'extended stay',
            'holiday inn',
            'hampton inn',
            'fairfield',
            'la quinta',
        ],
        tags: ['hotel', 'accommodation', 'lodging'],
        discoveryMethod: 'manual',
        confidence: 1.0,
        verifiedCount: 0,
    },
    {
        id: 'mcc_3398',
        code: '3398',
        categoryId: 'cat_travel',
        subCategoryId: 'subcat_car_rental',
        description: 'Car Rental Agencies',
        merchantPatterns: [
            'hertz',
            'enterprise',
            'avis',
            'budget',
            'national',
            'alamo',
            'thrifty',
            'dollar',
            'zipcar',
            'car2go',
            'turo',
        ],
        tags: ['car-rental', 'vehicle-hire', 'transportation'],
        discoveryMethod: 'manual',
        confidence: 1.0,
        verifiedCount: 0,
    },
    {
        id: 'mcc_4121',
        code: '4121',
        categoryId: 'cat_travel',
        subCategoryId: 'subcat_rideshare',
        description: 'Taxicabs and Limousines',
        merchantPatterns: [
            'uber',
            'lyft',
            'taxi',
            'cab',
            'rideshare',
            'limousine',
            'limo',
        ],
        tags: ['rideshare', 'taxi', 'transportation'],
        discoveryMethod: 'manual',
        confidence: 1.0,
        verifiedCount: 0,
    },

    // Shopping
    {
        id: 'mcc_5311',
        code: '5311',
        categoryId: 'cat_shopping',
        subCategoryId: 'subcat_department_stores',
        description: 'Department Stores',
        merchantPatterns: [
            'macys',
            'nordstrom',
            'jcpenney',
            'kohls',
            'dillards',
            'sears',
            'bloomingdales',
            'neiman marcus',
            'saks',
            'lord taylor',
        ],
        tags: ['department-store', 'retail', 'shopping'],
        discoveryMethod: 'manual',
        confidence: 1.0,
        verifiedCount: 0,
    },
    {
        id: 'mcc_5399',
        code: '5399',
        categoryId: 'cat_shopping',
        subCategoryId: 'subcat_online_shopping',
        description: 'Miscellaneous General Merchandise',
        merchantPatterns: [
            'amazon',
            'ebay',
            'etsy',
            'walmart.com',
            'target.com',
            'bestbuy.com',
            'costco.com',
            'wayfair',
            'overstock',
            'zappos',
        ],
        tags: ['online', 'e-commerce', 'general-merchandise'],
        discoveryMethod: 'manual',
        confidence: 1.0,
        verifiedCount: 0,
    },
    {
        id: 'mcc_5651',
        code: '5651',
        categoryId: 'cat_shopping',
        subCategoryId: 'subcat_clothing',
        description: 'Family Clothing Stores',
        merchantPatterns: [
            'gap',
            'old navy',
            'banana republic',
            'h&m',
            'forever 21',
            'zara',
            'uniqlo',
            'american eagle',
            'abercrombie',
            'hollister',
            'express',
        ],
        tags: ['clothing', 'apparel', 'fashion'],
        discoveryMethod: 'manual',
        confidence: 1.0,
        verifiedCount: 0,
    },
    {
        id: 'mcc_5732',
        code: '5732',
        categoryId: 'cat_shopping',
        subCategoryId: 'subcat_electronics',
        description: 'Electronics Stores',
        merchantPatterns: [
            'best buy',
            'apple store',
            'microsoft store',
            'frys',
            'micro center',
            'staples',
            'office depot',
            'radioshack',
        ],
        tags: ['electronics', 'technology', 'gadgets'],
        discoveryMethod: 'manual',
        confidence: 1.0,
        verifiedCount: 0,
    },

    // Entertainment
    {
        id: 'mcc_5815',
        code: '5815',
        categoryId: 'cat_entertainment',
        subCategoryId: 'subcat_streaming',
        description: 'Digital Goods - Media, Books, Movies, Music',
        merchantPatterns: [
            'netflix',
            'hulu',
            'disney plus',
            'amazon prime',
            'apple music',
            'spotify',
            'youtube premium',
            'hbo max',
            'paramount plus',
        ],
        tags: ['streaming', 'digital', 'subscription'],
        discoveryMethod: 'manual',
        confidence: 1.0,
        verifiedCount: 0,
    },
    {
        id: 'mcc_5813_movies',
        code: '5813',
        categoryId: 'cat_entertainment',
        subCategoryId: 'subcat_movies',
        description: 'Motion Picture Theaters',
        merchantPatterns: [
            'amc',
            'regal',
            'cinemark',
            'moviepass',
            'fandango',
            'atom tickets',
            'theater',
            'cinema',
            'movies',
        ],
        tags: ['movies', 'theater', 'entertainment'],
        discoveryMethod: 'manual',
        confidence: 1.0,
        verifiedCount: 0,
    },
    {
        id: 'mcc_5816',
        code: '5816',
        categoryId: 'cat_entertainment',
        subCategoryId: 'subcat_gaming',
        description: 'Digital Goods - Games',
        merchantPatterns: [
            'steam',
            'playstation',
            'xbox',
            'nintendo',
            'epic games',
            'blizzard',
            'riot games',
            'ea sports',
            'activision',
            'ubisoft',
        ],
        tags: ['gaming', 'video-games', 'digital'],
        discoveryMethod: 'manual',
        confidence: 1.0,
        verifiedCount: 0,
    },

    // Transportation
    {
        id: 'mcc_4111',
        code: '4111',
        categoryId: 'cat_transport',
        subCategoryId: 'subcat_public_transit',
        description: 'Transportation - Commuter Transport, Ferries',
        merchantPatterns: [
            'metro',
            'mta',
            'bart',
            'cta',
            'septa',
            'wmata',
            'transit',
            'bus',
            'subway',
            'train',
            'ferry',
            'clipper',
            'metrocard',
        ],
        tags: ['public-transit', 'commute', 'transportation'],
        discoveryMethod: 'manual',
        confidence: 1.0,
        verifiedCount: 0,
    },
    {
        id: 'mcc_7523',
        code: '7523',
        categoryId: 'cat_transport',
        subCategoryId: 'subcat_parking',
        description: 'Parking Lots and Garages',
        merchantPatterns: [
            'parkwhiz',
            'spothero',
            'parking',
            'garage',
            'meter',
            'valet',
        ],
        tags: ['parking', 'garage', 'meter'],
        discoveryMethod: 'manual',
        confidence: 1.0,
        verifiedCount: 0,
    },
    {
        id: 'mcc_4784',
        code: '4784',
        categoryId: 'cat_transport',
        subCategoryId: 'subcat_tolls',
        description: 'Bridge and Road Fees, Tolls',
        merchantPatterns: [
            'toll',
            'ezpass',
            'fastrak',
            'sunpass',
            'ipass',
            'bridge',
            'turnpike',
        ],
        tags: ['toll', 'bridge', 'highway'],
        discoveryMethod: 'manual',
        confidence: 1.0,
        verifiedCount: 0,
    },

    // Healthcare
    {
        id: 'mcc_8011',
        code: '8011',
        categoryId: 'cat_healthcare',
        subCategoryId: 'subcat_medical',
        description: 'Doctors',
        merchantPatterns: [
            'medical center',
            'clinic',
            'doctor',
            'physician',
            'hospital',
            'urgent care',
            'family practice',
            'internal medicine',
        ],
        tags: ['medical', 'healthcare', 'doctor'],
        discoveryMethod: 'manual',
        confidence: 1.0,
        verifiedCount: 0,
    },
    {
        id: 'mcc_5912',
        code: '5912',
        categoryId: 'cat_healthcare',
        subCategoryId: 'subcat_pharmacy',
        description: 'Drug Stores and Pharmacies',
        merchantPatterns: [
            'cvs',
            'walgreens',
            'rite aid',
            'pharmacy',
            'drugstore',
            'rx',
            'prescription',
            'medicine',
        ],
        tags: ['pharmacy', 'medication', 'drugstore'],
        discoveryMethod: 'manual',
        confidence: 1.0,
        verifiedCount: 0,
    },
    {
        id: 'mcc_8021',
        code: '8021',
        categoryId: 'cat_healthcare',
        subCategoryId: 'subcat_dental',
        description: 'Dentists, Orthodontists',
        merchantPatterns: [
            'dental',
            'dentist',
            'orthodontist',
            'oral surgery',
            'teeth cleaning',
        ],
        tags: ['dental', 'oral-health', 'dentist'],
        discoveryMethod: 'manual',
        confidence: 1.0,
        verifiedCount: 0,
    },

    // Utilities
    {
        id: 'mcc_4814',
        code: '4814',
        categoryId: 'cat_utilities',
        subCategoryId: null,
        description: 'Telecommunication Equipment and Telephone Sales',
        merchantPatterns: [
            'verizon',
            'att',
            't-mobile',
            'sprint',
            'comcast',
            'charter',
            'cox',
            'optimum',
            'fios',
            'xfinity',
            'spectrum',
        ],
        tags: ['telecom', 'phone', 'internet'],
        discoveryMethod: 'manual',
        confidence: 1.0,
        verifiedCount: 0,
    },
    {
        id: 'mcc_4900',
        code: '4900',
        categoryId: 'cat_utilities',
        subCategoryId: null,
        description: 'Utilities - Electric, Gas, Water, Sanitary',
        merchantPatterns: [
            'electric',
            'power',
            'gas company',
            'water',
            'utility',
            'energy',
            'pge',
            'con ed',
            'duke energy',
            'southern company',
        ],
        tags: ['utilities', 'electric', 'gas', 'water'],
        discoveryMethod: 'manual',
        confidence: 1.0,
        verifiedCount: 0,
    },

    // Financial Services
    {
        id: 'mcc_6011',
        code: '6011',
        categoryId: 'cat_finance',
        subCategoryId: null,
        description: 'Financial Institutions - ATM Fees, Bank Fees, etc.',
        merchantPatterns: [
            'bank of america',
            'chase',
            'wells fargo',
            'citi',
            'capital one',
            'usaa',
            'pnc',
            'td bank',
            'regions',
            'suntrust',
            'atm fee',
        ],
        tags: ['banking', 'finance', 'atm'],
        discoveryMethod: 'manual',
        confidence: 1.0,
        verifiedCount: 0,
    },

    // Home & Garden
    {
        id: 'mcc_5200',
        code: '5200',
        categoryId: 'cat_home',
        subCategoryId: null,
        description: 'Home Supply Warehouse Stores',
        merchantPatterns: [
            'home depot',
            'lowes',
            'menards',
            'home improvement',
            'hardware',
            'lumber',
            'building supply',
        ],
        tags: ['home-improvement', 'hardware', 'diy'],
        discoveryMethod: 'manual',
        confidence: 1.0,
        verifiedCount: 0,
    },
] as const;

/**
 * Seed MCC codes
 */
export async function seedMCCCodes(prisma: PrismaClient): Promise<void> {
    try {
        for (const mccCode of MCC_CODES) {
            await prisma.mCCCode.upsert({
                where: { code: mccCode.code },
                update: {
                    code: mccCode.code,
                    categoryId: mccCode.categoryId,
                    subCategoryId: mccCode.subCategoryId,
                    description: mccCode.description,
                    merchantPatterns: [...mccCode.merchantPatterns],
                    tags: [...mccCode.tags],
                    discoveryMethod: mccCode.discoveryMethod,
                    confidence: mccCode.confidence,
                    verifiedCount: mccCode.verifiedCount,
                },
                create: {
                    id: mccCode.id,
                    code: mccCode.code,
                    categoryId: mccCode.categoryId,
                    subCategoryId: mccCode.subCategoryId ?? null,
                    description: mccCode.description,
                    merchantPatterns: [...mccCode.merchantPatterns],
                    tags: [...mccCode.tags],
                    discoveryMethod: mccCode.discoveryMethod,
                    confidence: mccCode.confidence,
                    verifiedCount: mccCode.verifiedCount,
                },
            });
        }

        logger.info(`✅ Successfully seeded ${MCC_CODES.length} MCC codes`);
    } catch (error) {
        logger.error('❌ Error seeding MCC codes:', error);
        throw error;
    }
}
