import { PrismaClient } from '@prisma/client';
import { logger } from '../../shared/utils/logger.util';

/**
 * Comprehensive Indian merchant aliases to improve fuzzy matching accuracy
 * These help map various merchant name formats to proper MCC codes
 * Covers all major Indian brands across categories
 */
const INDIAN_MERCHANT_ALIASES = [
  // === FOOD DELIVERY & QUICK COMMERCE ===
  {
    id: 'alias_swiggy',
    merchantName: 'SWIGGY',
    aliases: [
      'Swiggy',
      'SWIGGY LIMITED',
      'SWIGGY LTD',
      'SWIGGY INSTAMART',
      'SWIGGY GENIE',
      'SWIGGY BOLT',
      'SWIGGYGENIE',
      'SWIGGYINSTAMART',
      'SNACC BY SWIGGY',
      'SNACC',
    ],
    mccCode: '5814',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_zomato',
    merchantName: 'ZOMATO',
    aliases: [
      'Zomato',
      'ZOMATO LIMITED',
      'ZOMATO LTD',
      'ZOMATO MEDIA',
      'ETERNAL LIMITED',
      'BLINKIT',
      'GROFERS',
      'BLINKIT BY ZOMATO',
    ],
    mccCode: '5814',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_blinkit',
    merchantName: 'BLINKIT',
    aliases: [
      'Blinkit',
      'GROFERS',
      'GROFERS INDIA',
      'BLINKIT LIMITED',
      'BLINKIT BY ZOMATO',
      'GROFERS TECHNOLOGIES',
    ],
    mccCode: '5499',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_zepto',
    merchantName: 'ZEPTO',
    aliases: [
      'Zepto',
      'ZEPTO INDIA',
      'ZEPTO LIMITED',
      'ZEPTO TECHNOLOGIES',
      'KiranaKart Technologies',
    ],
    mccCode: '5499',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_bigbasket',
    merchantName: 'BIGBASKET',
    aliases: [
      'BigBasket',
      'BIG BASKET',
      'BIGBASKET LIMITED',
      'BIGBASKET.COM',
      'BB NOW',
      'BBNOW',
      'BB INSTANT',
      'BBINSTANT',
      'SUPERMARKET GROCERY SUPPLIES',
    ],
    mccCode: '5411',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_dunzo',
    merchantName: 'DUNZO',
    aliases: [
      'Dunzo',
      'DUNZO DIGITAL',
      'DUNZO LIMITED',
      'DUNZO DELIVERY',
      'KABEER BISWAS',
    ],
    mccCode: '5814',
    confidence: 0.95,
    usageCount: 0,
    createdBy: 'indian_seed',
  },

  // === E-COMMERCE PLATFORMS ===
  {
    id: 'alias_flipkart',
    merchantName: 'FLIPKART',
    aliases: [
      'Flipkart',
      'FLIPKART INTERNET',
      'FLIPKART PRIVATE LIMITED',
      'FLIPKART.COM',
      'FLIPKART MINUTES',
      'FLIPKART GROCERY',
      'FLIPKART FASHION',
      'FLIPKART SUPERMART',
    ],
    mccCode: '5399',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_amazon_india',
    merchantName: 'AMAZON_INDIA',
    aliases: [
      'Amazon India',
      'AMAZON.IN',
      'AMAZON SELLER SERVICES',
      'AMAZON PAY INDIA',
      'AMAZON FRESH',
      'AMAZON PRIME',
      'AMAZON WEB SERVICES INDIA',
      'AWS INDIA',
      'AMAZON TRANSPORTATION',
    ],
    mccCode: '5399',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_myntra',
    merchantName: 'MYNTRA',
    aliases: [
      'Myntra',
      'MYNTRA DESIGNS',
      'MYNTRA.COM',
      'MYNTRA PRIVATE LIMITED',
      'MYNTRA FASHION',
    ],
    mccCode: '5651',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_ajio',
    merchantName: 'AJIO',
    aliases: [
      'AJIO',
      'AJIO.COM',
      'RELIANCE RETAIL VENTURES',
      'AJIO LUXE',
      'AJIO FASHION',
    ],
    mccCode: '5651',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_nykaa',
    merchantName: 'NYKAA',
    aliases: [
      'Nykaa',
      'NYKAA E-RETAIL',
      'NYKAA.COM',
      'NYKAA FASHION',
      'NYKAA BEAUTY',
      'FSN E-COMMERCE',
    ],
    mccCode: '5977',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_tatacliq',
    merchantName: 'TATACLIQ',
    aliases: [
      'TataCLiQ',
      'TATA CLIQ',
      'TATACLIQ.COM',
      'TATA UNISTORE',
      'TATA DIGITAL',
    ],
    mccCode: '5399',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_meesho',
    merchantName: 'MEESHO',
    aliases: [
      'Meesho',
      'MEESHO.COM',
      'MEESHO TECHNOLOGIES',
      'MEESHO PRIVATE LIMITED',
    ],
    mccCode: '5399',
    confidence: 0.95,
    usageCount: 0,
    createdBy: 'indian_seed',
  },

  // === TRANSPORTATION & RIDE-HAILING ===
  {
    id: 'alias_ola',
    merchantName: 'OLA',
    aliases: [
      'Ola',
      'OLA CABS',
      'OLACABS',
      'OLA MOBILITY',
      'ANI TECHNOLOGIES',
      'OLA MONEY',
      'OLAMONEY',
      'OLA ELECTRIC',
    ],
    mccCode: '4121',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_uber_india',
    merchantName: 'UBER_INDIA',
    aliases: [
      'Uber India',
      'UBER TECHNOLOGIES INDIA',
      'UBER INDIA SYSTEMS',
      'UBER BV INDIA',
      'UBER TRIP INDIA',
    ],
    mccCode: '4121',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_rapido',
    merchantName: 'RAPIDO',
    aliases: [
      'Rapido',
      'RAPIDO BIKE TAXI',
      'RAPIDO TECHNOLOGIES',
      'RAPIDO INDIA',
    ],
    mccCode: '4121',
    confidence: 0.95,
    usageCount: 0,
    createdBy: 'indian_seed',
  },

  // === TELECOM & RECHARGE ===
  {
    id: 'alias_jio',
    merchantName: 'JIO',
    aliases: [
      'Jio',
      'RELIANCE JIO',
      'RELIANCE JIO INFOCOMM',
      'JIO RECHARGE',
      'JIORECHARGE',
      'JIO FIBER',
      'JIOFIBER',
      'JIO MONEY',
      'JIOMONEY',
      'JIO MART',
      'JIOMART',
    ],
    mccCode: '4814',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_airtel',
    merchantName: 'AIRTEL',
    aliases: [
      'Airtel',
      'BHARTI AIRTEL',
      'AIRTEL INDIA',
      'AIRTEL RECHARGE',
      'AIRTEL MONEY',
      'AIRTEL XSTREAM',
      'AIRTEL FIBER',
      'AIRTEL DIGITAL TV',
      'AIRTEL PAYMENTS BANK',
    ],
    mccCode: '4814',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_vi',
    merchantName: 'VI',
    aliases: [
      'Vi',
      'VODAFONE IDEA',
      'VODAFONE',
      'IDEA CELLULAR',
      'IDEA',
      'VI RECHARGE',
      'VODAFONE RECHARGE',
      'IDEA RECHARGE',
    ],
    mccCode: '4814',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_bsnl',
    merchantName: 'BSNL',
    aliases: [
      'BSNL',
      'BHARAT SANCHAR NIGAM',
      'BSNL RECHARGE',
      'BSNL BROADBAND',
      'MAHANAGAR TELEPHONE NIGAM',
      'MTNL',
    ],
    mccCode: '4814',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },

  // === BANKING & FINTECH ===
  {
    id: 'alias_sbi',
    merchantName: 'SBI',
    aliases: [
      'SBI',
      'STATE BANK OF INDIA',
      'SBI CARD',
      'SBICARD',
      'SBI CARDS',
      'SBI PAYMENTS',
      'SBI YONO',
      'YONO SBI',
    ],
    mccCode: '6012',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_hdfc',
    merchantName: 'HDFC',
    aliases: [
      'HDFC',
      'HDFC BANK',
      'HDFC CARD',
      'HDFCBANK',
      'HDFC LIMITED',
      'HDFC PAYZAPP',
      'PAYZAPP',
    ],
    mccCode: '6012',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_icici',
    merchantName: 'ICICI',
    aliases: [
      'ICICI',
      'ICICI BANK',
      'ICICIBANK',
      'ICICI CARD',
      'ICICI POCKETS',
      'POCKETS',
      'ICICI PRUDENTIAL',
    ],
    mccCode: '6012',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_axis',
    merchantName: 'AXIS',
    aliases: [
      'Axis',
      'AXIS BANK',
      'AXISBANK',
      'AXIS CARD',
      'AXIS PAY',
      'AXIS MOBILE',
    ],
    mccCode: '6012',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_kotak',
    merchantName: 'KOTAK',
    aliases: [
      'Kotak',
      'KOTAK MAHINDRA',
      'KOTAK BANK',
      'KOTAK CARD',
      'KOTAK MAHINDRA BANK',
    ],
    mccCode: '6012',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_cred',
    merchantName: 'CRED',
    aliases: [
      'CRED',
      'CRED INDIA',
      'DREAMPLUG TECHNOLOGIES',
      'CRED PAY',
      'CREDPAY',
    ],
    mccCode: '6012',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_slice',
    merchantName: 'SLICE',
    aliases: [
      'Slice',
      'SLICE PAY',
      'SLICEPAY',
      'SLICE TECHNOLOGIES',
      'SLICE CARD',
    ],
    mccCode: '6012',
    confidence: 0.95,
    usageCount: 0,
    createdBy: 'indian_seed',
  },

  // === DIGITAL WALLETS & UPI ===
  {
    id: 'alias_paytm',
    merchantName: 'PAYTM',
    aliases: [
      'Paytm',
      'PAYTM MONEY',
      'PAYTM MALL',
      'PAYTM WALLET',
      'PAYTM PAYMENTS',
      'PAYTM RECHARGE',
      'ONE97 COMMUNICATIONS',
      'PAYTM MOVIES',
    ],
    mccCode: '6540',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_phonepe',
    merchantName: 'PHONEPE',
    aliases: [
      'PhonePe',
      'PHONE PE',
      'PHONEPE WALLET',
      'PHONEPE INDIA',
      'PHONEPE PRIVATE LIMITED',
    ],
    mccCode: '6540',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_googlepay',
    merchantName: 'GOOGLEPAY',
    aliases: [
      'Google Pay',
      'GOOGLE PAY',
      'GPAY',
      'G PAY',
      'GOOGLE PAYMENTS',
      'GOOGLE INDIA',
    ],
    mccCode: '6540',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_mobikwik',
    merchantName: 'MOBIKWIK',
    aliases: [
      'MobiKwik',
      'MOBI KWIK',
      'MOBIKWIK WALLET',
      'MOBIKWIK SYSTEMS',
      'ONE MOBIKWIK',
    ],
    mccCode: '6540',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_freecharge',
    merchantName: 'FREECHARGE',
    aliases: [
      'FreeCharge',
      'FREE CHARGE',
      'FREECHARGE PAYMENT',
      'FREECHARGE TECHNOLOGIES',
    ],
    mccCode: '6540',
    confidence: 0.95,
    usageCount: 0,
    createdBy: 'indian_seed',
  },

  // === FAST FOOD CHAINS ===
  {
    id: 'alias_mcdonalds_india',
    merchantName: 'MCDONALDS_INDIA',
    aliases: [
      "McDonald's India",
      'MCDONALDS INDIA',
      'MCD INDIA',
      'MCDONALDS #',
      'WESTLIFE DEVELOPMENT',
      'HARDCASTLE RESTAURANTS',
    ],
    mccCode: '5814',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_kfc_india',
    merchantName: 'KFC_INDIA',
    aliases: [
      'KFC India',
      'KFC',
      'KENTUCKY FRIED CHICKEN',
      'KFC RESTAURANT',
      'KFC #',
      'YUM BRANDS',
    ],
    mccCode: '5814',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_dominos_india',
    merchantName: 'DOMINOS_INDIA',
    aliases: [
      "Domino's India",
      'DOMINOS',
      'DOMINOS PIZZA',
      'DOMINOS #',
      'JUBILANT FOODWORKS',
    ],
    mccCode: '5814',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_pizzahut_india',
    merchantName: 'PIZZAHUT_INDIA',
    aliases: [
      'Pizza Hut India',
      'PIZZA HUT',
      'PIZZAHUT',
      'PIZZA HUT #',
      'YUM BRANDS INDIA',
    ],
    mccCode: '5814',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_subway_india',
    merchantName: 'SUBWAY_INDIA',
    aliases: [
      'Subway India',
      'SUBWAY',
      'SUBWAY SANDWICHES',
      'SUBWAY #',
    ],
    mccCode: '5814',
    confidence: 0.95,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_burgerking_india',
    merchantName: 'BURGERKING_INDIA',
    aliases: [
      'Burger King India',
      'BURGER KING',
      'BK INDIA',
      'BURGER KING #',
    ],
    mccCode: '5814',
    confidence: 0.95,
    usageCount: 0,
    createdBy: 'indian_seed',
  },

  // === COFFEE CHAINS ===
  {
    id: 'alias_starbucks_india',
    merchantName: 'STARBUCKS_INDIA',
    aliases: [
      'Starbucks India',
      'STARBUCKS',
      'STARBUCKS COFFEE',
      'STARBUCKS #',
      'TATA STARBUCKS',
    ],
    mccCode: '5499',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_ccd',
    merchantName: 'CCD',
    aliases: [
      'Cafe Coffee Day',
      'CCD',
      'CAFE COFFEE DAY',
      'COFFEE DAY',
      'CCD #',
      'COFFEE DAY ENTERPRISES',
    ],
    mccCode: '5499',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_chaayos',
    merchantName: 'CHAAYOS',
    aliases: [
      'Chaayos',
      'CHAAYOS INDIA',
      'CHAAYOS TEA',
      'CHAAYOS CAFE',
    ],
    mccCode: '5499',
    confidence: 0.95,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_chaipoint',
    merchantName: 'CHAIPOINT',
    aliases: [
      'Chai Point',
      'CHAI POINT',
      'CHAIPOINT',
      'TEA POINT',
    ],
    mccCode: '5499',
    confidence: 0.95,
    usageCount: 0,
    createdBy: 'indian_seed',
  },

  // === INDIAN RESTAURANT CHAINS ===
  {
    id: 'alias_haldirams',
    merchantName: 'HALDIRAMS',
    aliases: [
      'Haldirams',
      'HALDIRAM',
      'HALDIRAMS RESTAURANT',
      'HALDIRAM SNACKS',
      'HALDIRAMS FOODS',
    ],
    mccCode: '5812',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_barbequenation',
    merchantName: 'BARBEQUENATION',
    aliases: [
      'Barbeque Nation',
      'BARBEQUE NATION',
      'BBQ NATION',
      'BARBECUE NATION',
      'SAYAJI HOTELS',
    ],
    mccCode: '5812',
    confidence: 0.95,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_wowmomo',
    merchantName: 'WOWMOMO',
    aliases: [
      'Wow Momo',
      'WOW MOMO',
      'WOW! MOMO',
      'WOWMOMO FOODS',
    ],
    mccCode: '5814',
    confidence: 0.95,
    usageCount: 0,
    createdBy: 'indian_seed',
  },

  // === GROCERY CHAINS ===
  {
    id: 'alias_reliancefresh',
    merchantName: 'RELIANCEFRESH',
    aliases: [
      'Reliance Fresh',
      'RELIANCE FRESH',
      'RELIANCE RETAIL',
      'RELIANCE SMART',
      'RELIANCE DIGITAL',
    ],
    mccCode: '5411',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_dmart',
    merchantName: 'DMART',
    aliases: [
      'DMart',
      'D MART',
      'D-MART',
      'AVENUE SUPERMARTS',
      'DMART READY',
    ],
    mccCode: '5411',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_bigbazaar',
    merchantName: 'BIGBAZAAR',
    aliases: [
      'Big Bazaar',
      'BIG BAZAAR',
      'BIG BAZAR',
      'FUTURE RETAIL',
      'FOOD BAZAAR',
    ],
    mccCode: '5411',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_more',
    merchantName: 'MORE',
    aliases: [
      'More',
      'MORE SUPERMARKET',
      'MORE RETAIL',
      'MORE HYPERMARKET',
      'ADITYA BIRLA RETAIL',
    ],
    mccCode: '5411',
    confidence: 0.95,
    usageCount: 0,
    createdBy: 'indian_seed',
  },

  // === FUEL STATIONS ===
  {
    id: 'alias_indianoil',
    merchantName: 'INDIANOIL',
    aliases: [
      'Indian Oil',
      'INDIAN OIL',
      'IOCL',
      'IOC',
      'INDIAN OIL CORPORATION',
      'IOC PETROL PUMP',
    ],
    mccCode: '5541',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_bpcl',
    merchantName: 'BPCL',
    aliases: [
      'BPCL',
      'BHARAT PETROLEUM',
      'BP',
      'BHARAT PETROL PUMP',
      'BPCL FUEL',
    ],
    mccCode: '5541',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_hpcl',
    merchantName: 'HPCL',
    aliases: [
      'HPCL',
      'HINDUSTAN PETROLEUM',
      'HP',
      'HINDUSTAN PETROL PUMP',
      'HPCL FUEL',
    ],
    mccCode: '5541',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },

  // === ENTERTAINMENT & OTT ===
  {
    id: 'alias_hotstar',
    merchantName: 'HOTSTAR',
    aliases: [
      'Hotstar',
      'DISNEY HOTSTAR',
      'DISNEY+ HOTSTAR',
      'STAR INDIA',
      'HOTSTAR SUBSCRIPTION',
    ],
    mccCode: '5815',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_netflix_india',
    merchantName: 'NETFLIX_INDIA',
    aliases: [
      'Netflix India',
      'NETFLIX',
      'NETFLIX.COM',
      'NETFLIX SUBSCRIPTION',
    ],
    mccCode: '5815',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_bookmyshow',
    merchantName: 'BOOKMYSHOW',
    aliases: [
      'BookMyShow',
      'BOOK MY SHOW',
      'BMS',
      'BOOKMYSHOW.COM',
      'BIGTREE ENTERTAINMENT',
    ],
    mccCode: '7832',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_pvr',
    merchantName: 'PVR',
    aliases: [
      'PVR',
      'PVR CINEMAS',
      'PVR PICTURES',
      'PVR INOX',
      'PVR #',
    ],
    mccCode: '7832',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_inox',
    merchantName: 'INOX',
    aliases: [
      'INOX',
      'INOX CINEMAS',
      'INOX MOVIES',
      'INOX LEISURE',
      'PVR INOX',
    ],
    mccCode: '7832',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },

  // === HEALTHCARE ===
  {
    id: 'alias_apollo',
    merchantName: 'APOLLO',
    aliases: [
      'Apollo',
      'APOLLO HOSPITALS',
      'APOLLO PHARMACY',
      'APOLLO HEALTH',
      'APOLLO CLINICS',
    ],
    mccCode: '8062',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_1mg',
    merchantName: '1MG',
    aliases: [
      '1mg',
      'ONE MG',
      'ONEMG',
      '1MG TECHNOLOGIES',
      'HEALTHKART PLUS',
    ],
    mccCode: '5912',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_pharmeasy',
    merchantName: 'PHARMEASY',
    aliases: [
      'PharmEasy',
      'PHARM EASY',
      'PHARMEASY INDIA',
      'API HOLDINGS',
    ],
    mccCode: '5912',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_netmeds',
    merchantName: 'NETMEDS',
    aliases: [
      'Netmeds',
      'NET MEDS',
      'NETMEDS.COM',
      'NETMEDS MARKETPLACE',
    ],
    mccCode: '5912',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_medplus',
    merchantName: 'MEDPLUS',
    aliases: [
      'MedPlus',
      'MED PLUS',
      'MEDPLUS HEALTH',
      'MEDPLUS MART',
    ],
    mccCode: '5912',
    confidence: 0.95,
    usageCount: 0,
    createdBy: 'indian_seed',
  },

  // === EDUCATION & EDTECH ===
  {
    id: 'alias_byjus',
    merchantName: 'BYJUS',
    aliases: [
      "BYJU'S",
      'BYJUS',
      'BYJU S',
      'THINK AND LEARN',
      'BYJUS CLASSES',
    ],
    mccCode: '8299',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_unacademy',
    merchantName: 'UNACADEMY',
    aliases: [
      'Unacademy',
      'UNACADEMY GROUP',
      'SORTING HAT TECHNOLOGIES',
      'UNACADEMY PLUS',
    ],
    mccCode: '8299',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_vedantu',
    merchantName: 'VEDANTU',
    aliases: [
      'Vedantu',
      'VEDANTU INNOVATIONS',
      'VEDANTU LIVE',
      'VEDANTU CLASSES',
    ],
    mccCode: '8299',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },

  // === TRAVEL ===
  {
    id: 'alias_makemytrip',
    merchantName: 'MAKEMYTRIP',
    aliases: [
      'MakeMyTrip',
      'MAKE MY TRIP',
      'MMT',
      'MAKEMYTRIP.COM',
      'MAKEMYTRIP INDIA',
    ],
    mccCode: '4722',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_goibibo',
    merchantName: 'GOIBIBO',
    aliases: [
      'Goibibo',
      'GOIBIBO.COM',
      'GO IBIBO',
      'IBIBO GROUP',
    ],
    mccCode: '4722',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_cleartrip',
    merchantName: 'CLEARTRIP',
    aliases: [
      'Cleartrip',
      'CLEAR TRIP',
      'CLEARTRIP.COM',
      'CLEARTRIP INDIA',
    ],
    mccCode: '4722',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_irctc',
    merchantName: 'IRCTC',
    aliases: [
      'IRCTC',
      'INDIAN RAILWAYS',
      'INDIAN RAILWAY CATERING',
      'IRCTC.CO.IN',
      'RAILWAY BOOKING',
    ],
    mccCode: '4112',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_oyo',
    merchantName: 'OYO',
    aliases: [
      'OYO',
      'OYO ROOMS',
      'OYO HOTELS',
      'OYO LIFE',
      'ORAVEL STAYS',
    ],
    mccCode: '7011',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },

  // === AIRLINES ===
  {
    id: 'alias_indigo',
    merchantName: 'INDIGO',
    aliases: [
      'IndiGo',
      'INDIGO AIRLINES',
      'INTERGLOBE AVIATION',
      '6E',
      'INDIGO AIR',
    ],
    mccCode: '3000',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_airindia',
    merchantName: 'AIRINDIA',
    aliases: [
      'Air India',
      'AIR INDIA',
      'AI',
      'AIR INDIA LIMITED',
      'TATA SIA AIRLINES',
    ],
    mccCode: '3000',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_spicejet',
    merchantName: 'SPICEJET',
    aliases: [
      'SpiceJet',
      'SPICE JET',
      'SG',
      'SPICEJET LIMITED',
    ],
    mccCode: '3000',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_vistara',
    merchantName: 'VISTARA',
    aliases: [
      'Vistara',
      'VISTARA AIRLINES',
      'TATA SIA AIRLINES',
      'UK',
      'VISTARA AIR',
    ],
    mccCode: '3000',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },

  // === HOME SERVICES ===
  {
    id: 'alias_urbancompany',
    merchantName: 'URBANCOMPANY',
    aliases: [
      'Urban Company',
      'URBAN COMPANY',
      'URBANCLAP',
      'URBAN CLAP',
      'URBANCOMPANY INDIA',
    ],
    mccCode: '7349',
    confidence: 0.98,
    usageCount: 0,
    createdBy: 'indian_seed',
  },

  // === MISCELLANEOUS POPULAR BRANDS ===
  {
    id: 'alias_dream11',
    merchantName: 'DREAM11',
    aliases: [
      'Dream11',
      'DREAM 11',
      'DREAM SPORTS',
      'DREAM11 FANTASY',
    ],
    mccCode: '5816',
    confidence: 0.95,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
  {
    id: 'alias_zomatopro',
    merchantName: 'ZOMATOPRO',
    aliases: [
      'Zomato Pro',
      'ZOMATO PRO',
      'ZOMATO GOLD',
      'ZOMATO PLUS',
      'ZOMATO MEMBERSHIP',
    ],
    mccCode: '5815',
    confidence: 0.95,
    usageCount: 0,
    createdBy: 'indian_seed',
  },
] as const;

/**
 * Seed Indian merchant aliases
 */
export async function seedIndianMerchantAliases(prisma: PrismaClient): Promise<void> {
  try {
    for (const alias of INDIAN_MERCHANT_ALIASES) {
      await prisma.merchantAlias.upsert({
        where: { id: alias.id },
        update: {
          merchantName: alias.merchantName,
          aliases: [...alias.aliases],
          mccCode: alias.mccCode,
          confidence: alias.confidence,
          usageCount: alias.usageCount,
          createdBy: alias.createdBy,
        },
        create: {
          id: alias.id,
          merchantName: alias.merchantName,
          aliases: [...alias.aliases],
          mccCode: alias.mccCode,
          confidence: alias.confidence,
          usageCount: alias.usageCount,
          createdBy: alias.createdBy,
        },
      });
    }

    logger.info(
      `✅ Successfully seeded ${INDIAN_MERCHANT_ALIASES.length} Indian merchant aliases`,
    );
  } catch (error) {
    logger.error('❌ Error seeding Indian merchant aliases:', error);
    throw error;
  }
}